const RANKS = [
  { min: 0,    tier: 'IV',    label: 'RECRUIT COMMANDER' },
  { min: 150,  tier: 'III',   label: 'COMMANDER' },
  { min: 500,  tier: 'II',    label: 'SENIOR COMMANDER' },
  { min: 1100, tier: 'I',     label: 'ELITE COMMANDER' },
  { min: 2000, tier: 'PRIME', label: 'COMMANDER PRIME' },
  { min: 3500, tier: 'APEX',  label: 'COMMANDER APEX' }
];

const XP_TABLE = { LOW: 40, MED: 70, HIGH: 110, EXTREME: 180, '???': 250 };

const DieselState = {
  KEY: 'diesel_system_state_v1',

  defaults(){
    return {
      lockdown: false,
      broadcastCount: 0,
      claimedMissions: [],
      completedMissions: [],
      recruited: [],
      xp: 0,
      spotlight: false,
      soundOn: true,
      alerts: [],          // dynamic alerts generated by actions
      readAlerts: [],       // ids of read alerts (static + dynamic)
      messageReplies: {},   // { threadId: [ {who:'me'|'them', txt, t} ] }
      readMessages: [],
      accent: 'green',        // 'green' | 'cyan' | 'crimson' — UI accent theme
      transactions: [],       // dynamic wallet transactions generated by completed missions
      achievements: [],        // ids of unlocked achievements
      dispatches: [],          // { id, target, text, code, ts, status:'pending'|'done', reply, doneCode }
      firewallBlocks: 0        // counter for FIREWALL sweeps run from the map
    };
  },

  parseCurrency(str){
    if(typeof str !== 'string') return 0;
    const n = parseFloat(str.replace(/[^0-9.]/g, ''));
    return isNaN(n) ? 0 : n;
  },

  load(){
    let s;
    try{
      const raw = localStorage.getItem(this.KEY);
      s = raw ? JSON.parse(raw) : {};
    }catch(e){ s = {}; }
    // merge with defaults so old saves gain new fields safely
    return Object.assign(this.defaults(), s);
  },

  save(state){
    try{ localStorage.setItem(this.KEY, JSON.stringify(state)); }catch(e){}
  },

  get(){ return this.load(); },

  // ---------- core toggles ----------
  toggleLockdown(){
    const s = this.load();
    s.lockdown = !s.lockdown;
    this.save(s);
    this.addAlert('security', s.lockdown ? '&#128274;' : '&#128275;',
      s.lockdown ? 'System lockdown engaged — new connections held at the gate' : 'Lockdown disengaged — node open to new connections');
    const newAchievements = this.checkAchievements();
    return { lockdown: s.lockdown, newAchievements };
  },

  broadcast(){
    const s = this.load();
    s.broadcastCount++;
    this.save(s);
    this.addAlert('growth', '&#128227;', `Broadcast #${s.broadcastCount} reached all 15 units with zero drop-off`);
    const newAchievements = this.checkAchievements();
    return { count: s.broadcastCount, newAchievements };
  },

  // ---------- XP / rank ----------
  rankFor(xp){
    let current = RANKS[0];
    for(const r of RANKS){ if(xp >= r.min) current = r; }
    return current;
  },

  nextRank(xp){
    return RANKS.find(r => r.min > xp) || null;
  },

  addXp(amount){
    const s = this.load();
    const before = this.rankFor(s.xp);
    s.xp += amount;
    const after = this.rankFor(s.xp);
    this.save(s);
    const leveledUp = after.tier !== before.tier;
    if(leveledUp){
      this.addAlert('growth', '&#127942;', `Rank up — now ${after.label} (TIER ${after.tier})`);
    }
    return { xp: s.xp, before, after, leveledUp, gained: amount };
  },

  // ---------- missions ----------
  claimMission(id){
    const s = this.load();
    if(!s.claimedMissions.includes(id)) s.claimedMissions.push(id);
    this.save(s);
    return s;
  },

  completeMission(id, diff, reward, title){
    const s = this.load();
    const alreadyDone = s.completedMissions.includes(id);
    if(!alreadyDone) s.completedMissions.push(id);
    s.claimedMissions = s.claimedMissions.filter(m => m !== id);
    this.save(s);
    const gained = XP_TABLE[diff] || 50;
    const result = this.addXp(gained);
    this.addAlert('mission', '&#9989;', `Mission marked complete — +${gained} XP earned`);

    let tx = null;
    const amount = this.parseCurrency(reward);
    if(!alreadyDone && amount > 0){
      tx = this.addTransaction({
        title: (title || id) + ' — CONTRACT PAYOUT',
        desc: 'Contract closed and settled following mission completion.',
        amount, dir: 'in', tag: 'mission'
      });
    }
    const newAchievements = this.checkAchievements();
    return { ...result, tx, newAchievements };
  },

  isClaimed(id){ return this.load().claimedMissions.includes(id); },
  isCompleted(id){ return this.load().completedMissions.includes(id); },

  // ---------- wallet / transactions ----------
  addTransaction(tx){
    const s = this.load();
    const entry = Object.assign({
      id: 'tx_' + Date.now() + '_' + Math.floor(Math.random()*1000),
      date: 'just now',
      ts: Date.now()
    }, tx);
    s.transactions.unshift(entry);
    this.save(s);
    return entry;
  },

  walletTotals(seedTransactions, startingBalance){
    const all = [...this.load().transactions, ...(seedTransactions || [])];
    let totalIn = 0, totalOut = 0, largest = 0;
    all.forEach(t => {
      if(t.dir === 'in'){ totalIn += t.amount; if(t.amount > largest) largest = t.amount; }
      else totalOut += t.amount;
    });
    const balance = (startingBalance || 0) + totalIn - totalOut;
    return { balance, totalIn, totalOut, largest, all };
  },

  // ---------- achievements ----------
  checkAchievements(){
    const s = this.load();
    const unlocked = [];
    if(typeof ACHIEVEMENTS === 'undefined') return unlocked;
    ACHIEVEMENTS.forEach(a => {
      if(!s.achievements.includes(a.id) && a.test(s)){
        s.achievements.push(a.id);
        unlocked.push(a);
        this.addAlert('growth', a.icon || '&#127942;', `Achievement unlocked — ${a.name}`);
      }
    });
    if(unlocked.length) this.save(s);
    return unlocked;
  },

  // ---------- alerts ----------
  addAlert(kind, icon, msg){
    const s = this.load();
    const alert = { id: 'dyn_' + Date.now() + '_' + Math.floor(Math.random()*1000), kind, icon, msg, ts: Date.now() };
    s.alerts.unshift(alert);
    s.alerts = s.alerts.slice(0, 40); // cap history
    this.save(s);
    return alert;
  },

  markAlertsRead(ids){
    const s = this.load();
    ids.forEach(id => { if(!s.readAlerts.includes(id)) s.readAlerts.push(id); });
    this.save(s);
  },

  // ---------- messages ----------
  addReply(threadId, who, txt){
    const s = this.load();
    if(!s.messageReplies[threadId]) s.messageReplies[threadId] = [];
    s.messageReplies[threadId].push({ who, txt, t: Date.now() });
    this.save(s);
  },

  markMessageRead(threadId){
    const s = this.load();
    if(!s.readMessages.includes(threadId)) s.readMessages.push(threadId);
    this.save(s);
  },

  markAllMessagesRead(ids){
    const s = this.load();
    ids.forEach(id => { if(!s.readMessages.includes(id)) s.readMessages.push(id); });
    this.save(s);
  },

  // ---------- sound ----------
  toggleSound(){
    const s = this.load();
    s.soundOn = !s.soundOn;
    this.save(s);
    return s.soundOn;
  },

  // ---------- appearance ----------
  setAccent(accent){
    const s = this.load();
    s.accent = accent;
    this.save(s);
    if(window.DieselTheme) window.DieselTheme.apply(accent);
    return s;
  },

  // ---------- reset ----------
  resetProgress(){
    try{ localStorage.removeItem(this.KEY); }catch(e){}
  },

  // ---------- export / import ----------
  exportState(){
    return JSON.stringify(this.load(), null, 2);
  },

  importState(jsonText){
    try{
      const parsed = JSON.parse(jsonText);
      const merged = Object.assign(this.defaults(), parsed);
      this.save(merged);
      return true;
    }catch(e){
      return false;
    }
  },

  // ---------- map: dispatches (commands / org messages sent from the globe) ----------
  DISPATCH_DELAY_MS: 3 * 60 * 1000, // 3 minutes

  genCode(){
    const hex = () => Math.floor(Math.random()*0xffff).toString(16).toUpperCase().padStart(4,'0');
    return `${hex()}-${hex()}`;
  },

  addDispatch(target, text){
    const s = this.load();
    const entry = {
      id: 'dsp_' + Date.now() + '_' + Math.floor(Math.random()*1000),
      target, text,
      code: this.genCode(),
      ts: Date.now(),
      status: 'pending',
      reply: null,
      doneCode: null
    };
    s.dispatches.unshift(entry);
    s.dispatches = s.dispatches.slice(0, 60);
    this.save(s);
    return entry;
  },

  // resolves any pending dispatch whose 3-minute window has elapsed; returns newly resolved entries
  resolveDueDispatches(replyBank){
    const s = this.load();
    const justResolved = [];
    const now = Date.now();
    s.dispatches.forEach(d => {
      if(d.status === 'pending' && now - d.ts >= this.DISPATCH_DELAY_MS){
        d.status = 'done';
        d.doneCode = this.genCode();
        const bank = (replyBank && replyBank[d.target]) || ['Acknowledged. Directive carried out, no resistance met.'];
        d.reply = bank[Math.floor(Math.random()*bank.length)];
        this.addAlert('mission', '&#128225;', `${d.target} confirmed execution of your directive`);
        justResolved.push(d);
      }
    });
    if(justResolved.length) this.save(s);
    return justResolved;
  },

  getDispatches(){ return this.load().dispatches; },

  // ---------- map: firewall sweep ----------
  triggerFirewall(){
    const s = this.load();
    const blocked = 4 + Math.floor(Math.random()*9); // 4-12 flavor "threats blocked" per sweep
    s.firewallBlocks += blocked;
    this.save(s);
    this.addAlert('security', '&#128737;', `Firewall sweep complete — ${blocked} intrusion attempts blocked at the perimeter`);
    return { blocked, total: s.firewallBlocks };
  }
};
