const RANKS = [
  { min: 0,    tier: 'IV',    label: 'RECRUIT COMMANDER' },
  { min: 150,  tier: 'III',   label: 'COMMANDER' },
  { min: 500,  tier: 'II',    label: 'SENIOR COMMANDER' },
  { min: 1100, tier: 'I',     label: 'ELITE COMMANDER' },
  { min: 2000, tier: 'PRIME', label: 'COMMANDER PRIME' }
];

const XP_TABLE = { LOW: 40, MED: 70, HIGH: 110, EXTREME: 180, '???': 250 };

const DieselState = {
  KEY: 'diesel_system_state_v1',

  defaults(){
    return {
      lockdown: false,
      broadcastCount: 0,
      claimedMissions: [],
      completedMissions: [],
      recruited: [],
      xp: 0,
      spotlight: false,
      soundOn: true,
      alerts: [],          // dynamic alerts generated by actions
      readAlerts: [],       // ids of read alerts (static + dynamic)
      messageReplies: {},   // { threadId: [ {who:'me'|'them', txt, t} ] }
      readMessages: [],
      accent: 'green'        // 'green' | 'cyan' | 'crimson' — UI accent theme
    };
  },

  load(){
    let s;
    try{
      const raw = localStorage.getItem(this.KEY);
      s = raw ? JSON.parse(raw) : {};
    }catch(e){ s = {}; }
    // merge with defaults so old saves gain new fields safely
    return Object.assign(this.defaults(), s);
  },

  save(state){
    try{ localStorage.setItem(this.KEY, JSON.stringify(state)); }catch(e){}
  },

  get(){ return this.load(); },

  // ---------- core toggles ----------
  toggleLockdown(){
    const s = this.load();
    s.lockdown = !s.lockdown;
    this.save(s);
    this.addAlert('security', s.lockdown ? '&#128274;' : '&#128275;',
      s.lockdown ? 'System lockdown engaged — new connections held at the gate' : 'Lockdown disengaged — node open to new connections');
    return s.lockdown;
  },

  broadcast(){
    const s = this.load();
    s.broadcastCount++;
    this.save(s);
    this.addAlert('growth', '&#128227;', `Broadcast #${s.broadcastCount} reached all 12 units with zero drop-off`);
    return s.broadcastCount;
  },

  // ---------- XP / rank ----------
  rankFor(xp){
    let current = RANKS[0];
    for(const r of RANKS){ if(xp >= r.min) current = r; }
    return current;
  },

  nextRank(xp){
    return RANKS.find(r => r.min > xp) || null;
  },

  addXp(amount){
    const s = this.load();
    const before = this.rankFor(s.xp);
    s.xp += amount;
    const after = this.rankFor(s.xp);
    this.save(s);
    const leveledUp = after.tier !== before.tier;
    if(leveledUp){
      this.addAlert('growth', '&#127942;', `Rank up — now ${after.label} (TIER ${after.tier})`);
    }
    return { xp: s.xp, before, after, leveledUp, gained: amount };
  },

  // ---------- missions ----------
  claimMission(id){
    const s = this.load();
    if(!s.claimedMissions.includes(id)) s.claimedMissions.push(id);
    this.save(s);
    return s;
  },

  completeMission(id, diff){
    const s = this.load();
    if(!s.completedMissions.includes(id)) s.completedMissions.push(id);
    s.claimedMissions = s.claimedMissions.filter(m => m !== id);
    this.save(s);
    const gained = XP_TABLE[diff] || 50;
    const result = this.addXp(gained);
    this.addAlert('mission', '&#9989;', `Mission marked complete — +${gained} XP earned`);
    return result;
  },

  isClaimed(id){ return this.load().claimedMissions.includes(id); },
  isCompleted(id){ return this.load().completedMissions.includes(id); },

  // ---------- alerts ----------
  addAlert(kind, icon, msg){
    const s = this.load();
    const alert = { id: 'dyn_' + Date.now() + '_' + Math.floor(Math.random()*1000), kind, icon, msg, ts: Date.now() };
    s.alerts.unshift(alert);
    s.alerts = s.alerts.slice(0, 40); // cap history
    this.save(s);
    return alert;
  },

  markAlertsRead(ids){
    const s = this.load();
    ids.forEach(id => { if(!s.readAlerts.includes(id)) s.readAlerts.push(id); });
    this.save(s);
  },

  // ---------- messages ----------
  addReply(threadId, who, txt){
    const s = this.load();
    if(!s.messageReplies[threadId]) s.messageReplies[threadId] = [];
    s.messageReplies[threadId].push({ who, txt, t: Date.now() });
    this.save(s);
  },

  markMessageRead(threadId){
    const s = this.load();
    if(!s.readMessages.includes(threadId)) s.readMessages.push(threadId);
    this.save(s);
  },

  markAllMessagesRead(ids){
    const s = this.load();
    ids.forEach(id => { if(!s.readMessages.includes(id)) s.readMessages.push(id); });
    this.save(s);
  },

  // ---------- sound ----------
  toggleSound(){
    const s = this.load();
    s.soundOn = !s.soundOn;
    this.save(s);
    return s.soundOn;
  },

  // ---------- appearance ----------
  setAccent(accent){
    const s = this.load();
    s.accent = accent;
    this.save(s);
    if(window.DieselTheme) window.DieselTheme.apply(accent);
    return s;
  },

  // ---------- reset ----------
  resetProgress(){
    try{ localStorage.removeItem(this.KEY); }catch(e){}
  },

  // ---------- export / import ----------
  exportState(){
    return JSON.stringify(this.load(), null, 2);
  },

  importState(jsonText){
    try{
      const parsed = JSON.parse(jsonText);
      const merged = Object.assign(this.defaults(), parsed);
      this.save(merged);
      return true;
    }catch(e){
      return false;
    }
  }
};
